# Generated by Django 5.1.6 on 2025-02-24 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nmae',
            new_name='name',
        ),
    ]
